export { base16Vim, dkegVim } from './vim.js'
export { base16VimAirline, dkegVimAirline } from './vim-airline.js'
export { base16RxvtUnicode, dkegRxvtUnicode } from './rxvt-unicode.js'
export { base16I3, dkegI3 } from './i3.js'
export { base16I3Status, dkegI3Status } from './i3-status.js'
export { dkegRofi } from './rofi.js'
